### ISSUE TITLE
Error compiling for board DOIT ESP32 DEVKIT V1

### ISSUE THREAD

**Issue by Alfinza** [hansjny/Natural-Nerd#11]
Arduino: 1.8.9 (Windows Store 1.8.21.0) (Windows 10), Board: "DOIT ESP32 DEVKIT V1, 80MHz, 115200, None"

In file included from C:\Users\Alfinza SP\Documents\Arduino\nano\nano.ino:2:0:

C:\Users\Alfinza SP\Documents\Arduino\libraries\FastLED/FastLED.h:14:21: note: #pragma message: FastLED version 3.002.006

 #    pragma message "FastLED version 3.002.006"

                     ^

In file included from C:\Users\Alfinza SP\Documents\Arduino\libraries\FastLED/FastLED.h:65:0,

                 from C:\Users\Alfinza SP\Documents\Arduino\nano\nano.ino:2:

C:\Users\Alfinza SP\Documents\Arduino\libraries\FastLED/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

C:\Users\ALFINZ~1\AppData\Local\Temp\arduino_cache_380355\core\core_cbb7e869e3f9c843d6b130e7441b3c37.a(main.cpp.o):(.literal._Z8loopTaskPv+0x4): undefined reference to `setup()'

C:\Users\ALFINZ~1\AppData\Local\Temp\arduino_cache_380355\core\core_cbb7e869e3f9c843d6b130e7441b3c37.a(main.cpp.o):(.literal._Z8loopTaskPv+0x8): undefined reference to `loop()'

C:\Users\ALFINZ~1\AppData\Local\Temp\arduino_cache_380355\core\core_cbb7e869e3f9c843d6b130e7441b3c37.a(main.cpp.o): In function `loopTask(void*)':

C:\Users\Alfinza SP\Documents\Arduino\hardware\espressif\esp32\cores\esp32/main.cpp:14: undefined reference to `setup()'

C:\Users\Alfinza SP\Documents\Arduino\hardware\espressif\esp32\cores\esp32/main.cpp:17: undefined reference to `loop()'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board DOIT ESP32 DEVKIT V1.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by hansjny** [comment]
```C:\Users\ALFINZ~1\AppData\Local\Temp\arduino_cache_380355\core\core_cbb7e869e3f9c843d6b130e7441b3c37.a(main.cpp.o):(.literal._Z8loopTaskPv+0x4): undefined reference to `setup()'

C:\Users\ALFINZ~1\AppData\Local\Temp\arduino_cache_380355\core\core_cbb7e869e3f9c843d6b130e7441b3c37.a(main.cpp.o):(.literal._Z8loopTaskPv+0x8): undefined reference to `loop()'```

Not related to this code
