### ISSUE TITLE
error: FastLED.h: No such file or directory

### ISSUE THREAD

**Issue by renaudmarique** [hansjny/Natural-Nerd#12]
Hello, i'm verry bad in arduino and i need your help, so i want to do the project with the LED and they give me a error message; error: FastLED.h: No such file or directory
i try everything but nothing changed, can someone help me please ?

**Comment by magicwoody** [comment]
HI, you have to add the library for fastled first into your arduino programming software. For IDE under Tools / Manage Libraries - search fastled and install - good lick

**Comment by massi102811** [comment]
Mi dice no directory per il led.h, cosa devo fare per risolvere il problema.
