### ISSUE TITLE
If you have a *nervous* Flicker or the Lights don't lower if no Music

### ISSUE THREAD

**Issue by magicwoody** [hansjny/Natural-Nerd#13]
I noticed a permanent high level in the lights, also if there was no sound.

Figured out that this is not happen by USB connection to the Master. Struggeling a long time found the solution.
For Master i use a NodeMCU with 5V input, the 3,7 from Batterie was too *low*
Just add a step up converter between batterie and NodeMCU, tune it to 5 Volt and get to the 5 Volt input. Works fine now.

This is no issue but a Tip for others who build this.

**Comment by vaibhav4verma** [comment]
I am getting error - reactive_common.h: No such file or directory, only you can help
