### ISSUE TITLE
Leds turn on and still white

### ISSUE THREAD

**Issue by Danilodo82** [hansjny/Natural-Nerd#15]
hello, I programmed esp32, the blynk application communicates correctly but when I connect the LEDs to esp32, light up and remain white. can you help me please?
P.S. I used a 5v led strip

**Comment by Netto09** [comment]
Question 1: I am trying to control by the Blynk application but it did not work. Any idea what changes I should make in the code?
Question 2: How to change chorma in "void chillFade ()"?

**Comment by Netto09** [comment]
To use Blynk, I inserted all the codes used by the application libraries and changed the WiFi.mode (WIFI_AP) to "wifi_ap_sta" in master.ino. But it did not work.

P.S .: I am using NodeMCU and Wi-Fi connection for communication with application.

**Comment by hansjny** [comment]
Cleaning old issues, closing this.
