### ISSUE TITLE
Error when Verifying file before upload.

### ISSUE THREAD

**Issue by onimo** [hansjny/Natural-Nerd#2]
Arduino: 1.6.6 (Mac OS X), Board: "Arduino Nano, ATmega328"

Warning: platform.txt from core 'Adafruit SAMD Boards' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{archive_file_path}" "{object_file}". Consider upgrading this core.
Warning: platform.txt from core 'Leonardo & Micro MIDI-USB (arcore)' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{archive_file_path}" "{object_file}". Consider upgrading this core.
WARNING: Spurious .github folder in 'Adafruit NeoPixel' library
avr-g++: error: missing filename after '-o'
exit status 1
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

Only thing I changed is NUM_LEDS from 150 to 60

**Comment by hansjny** [comment]
Seems like there is something wrong with the inclusion?
