### ISSUE TITLE
Error in compiling on both sets of code

### ISSUE THREAD

**Issue by njennin12** [hansjny/Natural-Nerd#21]
I apologize for the formatting it was the only way i could find to copy the error codes. 

The error codes are as followed:(for the master code): 
In file included from C:\Users\jenni\OneDrive\Documents\Arduino\LAMPS_MASTER\LAMPS_MASTER.ino:1:0:

C:\Users\jenni\OneDrive\Documents\Arduino\libraries\FastLED-3.3.0/FastLED.h:14:21: note: #pragma message: FastLED version 3.003.000

 #    pragma message "FastLED version 3.003.000"

                     ^

In file included from C:\Users\jenni\OneDrive\Documents\Arduino\libraries\FastLED-3.3.0/FastLED.h:65:0,

                 from C:\Users\jenni\OneDrive\Documents\Arduino\LAMPS_MASTER\LAMPS_MASTER.ino:1:

C:\Users\jenni\OneDrive\Documents\Arduino\libraries\FastLED-3.3.0/fastspi.h:130:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

C:\Users\jenni\OneDrive\Documents\Arduino\LAMPS_MASTER\LAMPS_MASTER.ino: In function 'void readHeartBeat()':

LAMPS_MASTER:116:28: error: aggregate 'readHeartBeat()::heartbeat_message hbm' has incomplete type and cannot be defined

   struct heartbeat_message hbm;

                            ^

LAMPS_MASTER:122:57: error: invalid application of 'sizeof' to incomplete type 'readHeartBeat()::heartbeat_message'

   UDP.read((char *)&hbm, sizeof(struct heartbeat_message));

                                                         ^

Using library FastLED-3.3.0 at version 3.3.0 in folder: C:\Users\jenni\OneDrive\Documents\Arduino\libraries\FastLED-3.3.0 
Using library ESP8266WiFi at version 1.0 in folder: C:\Users\jenni\OneDrive\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WiFi 
Using library reactive_common.h in folder: C:\Users\jenni\OneDrive\Documents\Arduino\libraries\reactive_common.h (legacy)
exit status 1
aggregate 'readHeartBeat()::heartbeat_message hbm' has incomplete type and cannot be defined

And for the slave code: 

In file included from C:\Users\jenni\OneDrive\Documents\Arduino\LAMPS_SLAVE\LAMPS_SLAVE.ino:3:0:

C:\Users\jenni\OneDrive\Documents\Arduino\libraries\FastLED-3.3.0/FastLED.h:14:21: note: #pragma message: FastLED version 3.003.000

 #    pragma message "FastLED version 3.003.000"

                     ^

In file included from C:\Users\jenni\OneDrive\Documents\Arduino\libraries\FastLED-3.3.0/FastLED.h:65:0,

                 from C:\Users\jenni\OneDrive\Documents\Arduino\LAMPS_SLAVE\LAMPS_SLAVE.ino:3:

C:\Users\jenni\OneDrive\Documents\Arduino\libraries\FastLED-3.3.0/fastspi.h:130:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

C:\Users\jenni\OneDrive\Documents\Arduino\LAMPS_SLAVE\LAMPS_SLAVE.ino: In function 'void setup()':

LAMPS_SLAVE:53:43: error: invalid use of incomplete type 'struct averageCounter'

   samples = new averageCounter(SAMPLE_SIZE);

                                           ^

LAMPS_SLAVE:27:8: error: forward declaration of 'struct averageCounter'

 struct averageCounter *samples;

        ^

LAMPS_SLAVE:54:57: error: invalid use of incomplete type 'struct averageCounter'

   longTermSamples = new averageCounter(LONG_TERM_SAMPLES);

                                                         ^

LAMPS_SLAVE:27:8: error: forward declaration of 'struct averageCounter'

 struct averageCounter *samples;

        ^

LAMPS_SLAVE:55:51: error: invalid use of incomplete type 'struct averageCounter'

   sanityBuffer    = new averageCounter(BUFFER_SIZE);

                                                   ^

LAMPS_SLAVE:27:8: error: forward declaration of 'struct averageCounter'

 struct averageCounter *samples;

        ^

LAMPS_SLAVE:57:21: error: invalid use of incomplete type 'struct averageCounter'

   while(sanityBuffer->setSample(250) == true) {}

                     ^

LAMPS_SLAVE:27:8: error: forward declaration of 'struct averageCounter'

 struct averageCounter *samples;

        ^

LAMPS_SLAVE:58:25: error: invalid use of incomplete type 'struct averageCounter'

   while (longTermSamples->setSample(200) == true) {}

                         ^

LAMPS_SLAVE:27:8: error: forward declaration of 'struct averageCounter'

 struct averageCounter *samples;

        ^

C:\Users\jenni\OneDrive\Documents\Arduino\LAMPS_SLAVE\LAMPS_SLAVE.ino: In function 'void sendHeartBeat()':

LAMPS_SLAVE:77:30: error: aggregate 'sendHeartBeat()::heartbeat_message hbm' has incomplete type and cannot be defined

     struct heartbeat_message hbm;

                              ^

C:\Users\jenni\OneDrive\Documents\Arduino\LAMPS_SLAVE\LAMPS_SLAVE.ino: In function 'void soundReactive(int)':

LAMPS_SLAVE:186:32: error: invalid use of incomplete type 'struct averageCounter'

  int sanityValue = sanityBuffer->computeAverage();

                                ^

LAMPS_SLAVE:27:8: error: forward declaration of 'struct averageCounter'

 struct averageCounter *samples;

        ^

LAMPS_SLAVE:188:17: error: invalid use of incomplete type 'struct averageCounter'

     sanityBuffer->setSample(analogRaw);

                 ^

LAMPS_SLAVE:27:8: error: forward declaration of 'struct averageCounter'

 struct averageCounter *samples;

        ^

LAMPS_SLAVE:192:14: error: invalid use of incomplete type 'struct averageCounter'

   if (samples->setSample(analogRaw))

              ^

LAMPS_SLAVE:27:8: error: forward declaration of 'struct averageCounter'

 struct averageCounter *samples;

        ^

LAMPS_SLAVE:195:45: error: invalid use of incomplete type 'struct averageCounter'

   uint16_t longTermAverage = longTermSamples->computeAverage();

                                             ^

LAMPS_SLAVE:27:8: error: forward declaration of 'struct averageCounter'

 struct averageCounter *samples;

        ^

LAMPS_SLAVE:196:28: error: invalid use of incomplete type 'struct averageCounter'

   uint16_t useVal = samples->computeAverage();

                            ^

LAMPS_SLAVE:27:8: error: forward declaration of 'struct averageCounter'

 struct averageCounter *samples;

        ^

LAMPS_SLAVE:197:18: error: invalid use of incomplete type 'struct averageCounter'

   longTermSamples->setSample(useVal);

                  ^

LAMPS_SLAVE:27:8: error: forward declaration of 'struct averageCounter'

 struct averageCounter *samples;

        ^

Using library FastLED-3.3.0 at version 3.3.0 in folder: C:\Users\jenni\OneDrive\Documents\Arduino\libraries\FastLED-3.3.0 
Using library ESP8266WiFi at version 1.0 in folder: C:\Users\jenni\OneDrive\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WiFi 
Using library reactive_common.h in folder: C:\Users\jenni\OneDrive\Documents\Arduino\libraries\reactive_common.h (legacy)
exit status 1
invalid use of incomplete type 'struct averageCounter'

Thank you in advance

**Comment by hansjny** [comment]
Can't reproduce.
