### ISSUE TITLE
Reactive_common.h no such file or direcrory

### ISSUE THREAD

**Issue by QuaserDaser** [hansjny/Natural-Nerd#22]
Hi,
When I try compiling the led_slave or master this error occures. I included all libaries but I dont know what to do with the reactive_common.h. where do I have to put it so it includes it?
Thanks in advance.

**Comment by CARPER1963** [comment]
Hola, en la misma carpeta que esta el archivo .iso

**Comment by amercer86** [comment]
> 
> 
> Hi,
> When I try compiling the led_slave or master this error occures. I included all libaries but I dont know what to do with the reactive_common.h. where do I have to put it so it includes it?
> Thanks in advance.

I can't get this to work either. :(

**Comment by akhil-intronerd** [comment]
Hey guysIi found the solution for this, its pretty simple actually. There is a file included in the main folder named 'reactive_common.h'
Just open Arduino IDE and goto Toolbar>Sketch>Add File
then locate & select 'reactive_common.h' file from the folder included and done!

**Comment by akhil-intronerd** [comment]
Hey guys! I found the solution for this, its pretty simple actually. There is a file included in the main folder named 'reactive_common.h'
Just open Arduino IDE and goto Toolbar>Sketch>Add File
then locate & select 'reactive_common.h' file from the folder included and done!
Also you'll have to do this while uploading both Master & Slave files as it opens this library in other tab in Arduino IDE.

**Comment by akhil-intronerd** [comment]
Hey guys! I found the solution for this, its pretty simple actually. There is a file included in the main folder named 'reactive_common.h'
Just open Arduino IDE and go to Toolbar>Sketch>Add File
then locate & select 'reactive_common.h' file from the folder included and done!
Also you'll have to do this while uploading both Master & Slave files as it opens this library in other tab in Arduino IDE.
