### ISSUE TITLE
issue upcode Uno R3 MCU with CH340G Chip.

### ISSUE THREAD

**Issue by Artyorm** [hansjny/Natural-Nerd#3]
sound_reactive.ino:1:21: fatal error: FastLED.h: No such file or directory
 #include <FastLED.h>

                     ^
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino Uno.
This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

I use Uno R3 MCU Board DCC Version with CH340G Chip, when upcode is error as above

**Comment by Artyorm** [comment]
upcode ok

**Comment by hansjny** [comment]
You must install the FastLED library.
