### ISSUE TITLE
Soundreactive2 error with readheartbeat

### ISSUE THREAD

**Issue by nislandj** [hansjny/Natural-Nerd#33]
I'm hoping you can help me out here, in the soundreactive master code I get these errors when I verify the code. Its not the whole error message but its what looked important at the time. Any help would be appreciated.

#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

In function 'void readHeartBeat()': floor_lamps_2.0_master:116:28: error: aggregate 'readHeartBeat()::heartbeat_message hbm' has incomplete type and cannot be defined struct heartbeat_message hbm;

invalid application of 'sizeof' to incomplete type 'readHeartBeat()::heartbeat_message' UDP.read((char *)&hbm, sizeof(struct heartbeat_message));

exit status 1
aggregate 'readHeartBeat()::heartbeat_message hbm' has incomplete type and cannot be defined

**Comment by hansjny** [comment]
I can't replicate, I think you're doing something wrong.
