### ISSUE TITLE
Using just 9 LEDs

### ISSUE THREAD

**Issue by SmilingJack85** [hansjny/Natural-Nerd#4]
I tried to use your code for a project with just 9 LEDs, but i don´t get an animation. The lights just flicker red "randomly". 
The soundchip reacts correctly according to the led on it.
Any idea how to use your code for such a small amount of LEDs?

**Comment by hansjny** [comment]
If you are talking about sound reactive, I would look into this call: 
`mapped = (float)fscale(MIC_LOW, MIC_HIGH, MIC_LOW, (float)MIC_HIGH, (float)sensor_value, 2.0);`

Play with the 2,0. Try for instance -5 or +5 and see if it does a difference.  I have only tried it with a minimum of 30 LEDs.
